# Generated by Django 5.0.6 on 2026-09-17 12:52

import delegates.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('tenant_id', models.CharField(blank=True, default='', max_length=128)),
                ('delegate_id', models.CharField(blank=True, default='', max_length=64)),
                ('execution_id', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('queue', models.CharField(default='default', max_length=128)),
                ('concurrency', models.IntegerField(default=1)),
                ('cert_serial', models.CharField(max_length=64)),
                ('cert_pem', models.TextField()),
                ('cert_expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('token', models.CharField(default=delegates.models._generate_token, max_length=64, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('execution_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=128)),
                ('workspace_fixture', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('TRANSFERRING', 'Transferring'), ('TRANSFER_FAILED', 'Transfer failed'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('transfer_id', models.CharField(blank=True, default='', max_length=64)),
                ('transfer_attempts', models.IntegerField(default=0)),
                ('output_path', models.CharField(blank=True, default='', max_length=256)),
                ('output_checksum', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='delegates.delegate')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('line', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='delegates.execution')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
    ]
